# DO NOT REMOVE THIS
theme = "hugo-theme-codex" 

# Override these settings with your own
# 用你自己的设置覆盖这些设置
title = "iksrr's blog"
languageCode = "zh-CN"
# baseURL = "http://example.com/"
baseURL = "https://iksrr.tk/"
copyright = "© 2022"

# Add your Disqus shortname here.
# 在这里添加你的Discuz短名
disqusShortname = "iksrr"

# Add your Google Analytics identifier: UA-XXXXXXXX-X
# 添加你的谷歌分析标识符
# googleAnalytics = "UA-150435252-1" 

# Optional params
# 可选参数
[params]
  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  # 按照雨果的日期/时间格式,参考这里
  dateFormat = "Jan 2 2006"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  # 链接到你的社交账户，根据需要评论/取消评论。图标将显示为指定的那些。
  # twitter = "https://twitter.com/<your handle>"
  github = "https://github.com/jmzdd"
  email = "mailto:2041418454@qq.com"
  zhihu = "https://www.zhihu.com/people/jian-mo-zhong-deng-dai"
  bilibili = "https://space.bilibili.com/109396152"
  wymusic = "https://music.163.com/#/user/home?id=1469345720"

  # mastodon = "https://mastodon.social/@nickname"
  # facebook = "https://facebook.com/<your handle>"
  # gitlab = "https://gitlab.com/<your handle>"
  # instagram = "https://instagram.com/<your handle>"
  # linkedin = "<link to your profile>"
  # youtube = "https://www.youtube.com/channel/<your channel>"
  
  # Titles for your icons (shown as tooltips), and also their display order.
  # 你的图标的标题（作为工具提示显示），以及它们的显示顺序
  # Currently, these icons are supported: 
  #   "Twitter", "GitHub", "Email", "Mastodon", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconOrder = ["gitHub","email","zhihu","bilibili","wymusic"]

  # Metadata for Twitter cards, defaults to params.twitter
  # twitter卡片的元数据，默认为params.twitter
  # twitterSite = "@<your handle>"
  # twitterAuthor = "@<your handle>"

  # Set to true to display page title in table of contents in blog posts.
  # 设置为 "true"，在博客文章的目录中显示页面标题。
  showPageTitleInTOC = true

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
# 这将禁用Hugo的默认语法高亮，而采用
# 语法高亮。如果你想使用Hugo的默认语法高亮
# 而不是Prismjs，请删除此项。你还需要删除 prismjs
# 厂商的脚本。
[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  # 设置为false以禁止在markdown文件中使用原始HTML
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"
