# DO NOT REMOVE THIS
theme = "hugo-theme-codex" 

# 用你自己的设置覆盖这些设置
title = "jmzdd's blog"
languageCode = "zh-CN"
baseURL = "https://iksrr.tk/"
copyright = "© {2022}"

# 在这里添加你的Discuz短名
# disqusShortname = ""

# 添加你的谷歌分析标识符
# googleAnalytics = "" 

# Optional params
[params]
  # 按照雨果的日期/时间格式,参考这里 
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"

  # 链接到你的社交账户，根据需要评论/取消评论。图标将显示为指定的那些。
  twitter = "https://twitter.com/<your handle>"
  github = "https://github.com/jmzdd"
  # email = "mailto:<your email>"
  # mastodon = "https://mastodon.social/@nickname"
  # facebook = "https://facebook.com/<your handle>"
  # gitlab = "https://gitlab.com/<your handle>"
  # instagram = "https://instagram.com/<your handle>"
  # linkedin = "<link to your profile>"
  # youtube = "https://www.youtube.com/channel/<your channel>"
  
  # 你的图标的标题（作为工具提示显示），以及它们的显示顺序
  # Currently, these icons are supported: 
  #   "Twitter", "GitHub", "Email", "Mastodon", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconOrder = ["GitHub"]

  # Metadata for Twitter cards, defaults to params.twitter
  # twitterSite = "@<your handle>"
  # twitterAuthor = "@<your handle>"

  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = false

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"



